Fix a problem about device (#141)
Specifies the device to fix a bug: Loading the GPU model to the CPU will cause an exception
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```